name: 'PR Comment Action'
description: 'Adds a comment to the PR that triggered the workflow'
author: 'GH-Action-Creator'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  comment-message:
    description: 'The message to add as a comment to the PR'
    required: true
  include-timestamp:
    description: 'Whether to include a timestamp in the comment'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Add comment to PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMENT_MESSAGE: ${{ inputs.comment-message }}
        INCLUDE_TIMESTAMP: ${{ inputs.include-timestamp }}
      run: |
        echo "Adding comment to PR..."
        # Error handling for non-PR events
        if [ ! -f "$GITHUB_EVENT_PATH" ]; then
          echo "::error::Event file not found at $GITHUB_EVENT_PATH"
          exit 1
        fi
        
        # Check if this is a pull request event
        if ! jq -e '.pull_request' "$GITHUB_EVENT_PATH" > /dev/null; then
          echo "::error::This action only works on pull request events"
          exit 1
        fi
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        REPO_OWNER=$(jq --raw-output .repository.owner.login "$GITHUB_EVENT_PATH")
        REPO_NAME=$(jq --raw-output .repository.name "$GITHUB_EVENT_PATH")
        
        COMMENT="$COMMENT_MESSAGE"
        if [[ "$INCLUDE_TIMESTAMP" == "true" ]]; then
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          COMMENT="$COMMENT_MESSAGE
          
          _Timestamp: $TIMESTAMP_"
        fi
        
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments" \
          -d "{\"body\":\"$COMMENT\"}")
        
        COMMENT_URL=$(echo "$RESPONSE" | jq --raw-output .html_url)
        COMMENT_ID=$(echo "$RESPONSE" | jq --raw-output .id)
          
        echo "Comment added: $COMMENT_URL"
        # Use the newer GitHub Actions output syntax
        echo "comment-url=$COMMENT_URL" >> $GITHUB_OUTPUT
        echo "comment-id=$COMMENT_ID" >> $GITHUB_OUTPUT

branding:
  icon: 'message-circle'
  color: 'blue'
